In [2]:
import tensorflow as tf

In [3]:
a= tf.constant(100)
b= tf.constant(20)
with tf.Session() as sess:
    result = sess.run(a+b)
print(result)

120


In [4]:
fill_mat = tf.fill((4,4),10)
myzeros = tf.zeros((4,4))
myones = tf.ones((4,4))
myrandn = tf.random_normal((4,4),mean=0,stddev=1.0)
myrandu = tf.random_uniform((4,4),minval=0.0,maxval=1.0)
my_ops = [fill_mat,myzeros,myones,myrandn,myrandu]

sess = tf.InteractiveSession()
for op in my_ops:
    print(sess.run(op)) # op.eval()
    print('\n')

[[10 10 10 10]
 [10 10 10 10]
 [10 10 10 10]
 [10 10 10 10]]


[[0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]]


[[0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]]


[[ 0.785133    0.11480697 -0.09137132  0.5968584 ]
 [ 3.3958538   0.6931504   1.6756667   0.87044966]
 [ 1.191872   -0.04665197  0.8724494   0.02992201]
 [ 0.6050213   0.98248553  0.8840305  -0.05914465]]


[[0.57780087 0.7012147  0.0689882  0.26604366]
 [0.79983926 0.9783616  0.08700562 0.40899038]
 [0.8790586  0.5578145  0.00373673 0.67460084]
 [0.935143   0.61058116 0.86031175 0.30702496]]




In [5]:
a = tf.constant([[1,2],
                 [3,4]])
a.get_shape()

TensorShape([Dimension(2), Dimension(2)])

In [8]:
b=tf.constant([[10],[100]])
b.get_shape()

TensorShape([Dimension(2), Dimension(1)])

In [9]:
result = tf.matmul(a,b)
sess.run(result)

array([[210],
       [430]], dtype=int32)

In [10]:
result.eval()

array([[210],
       [430]], dtype=int32)